### ISSUE TITLE
MCParticles created in the simulation are not drawn by DDCEDViewer

### ISSUE THREAD

**Issue by Zehvogel** [iLCSoft/CEDViewer#26]
They have generator status 0.
The culprit:

https://github.com/iLCSoft/CEDViewer/blob/eec6d2391ca5bd735e402eb17de192863f959d62/src/DDCEDViewer.cc#L646-L653

Results in not being able to figure out what all the particles are in events like this (single muon having an interaction in the tracker): 

![image](https://github.com/user-attachments/assets/6c66798d-1a56-40dc-b574-dcba1c503530)

The obvious workaround is to run with `usingParticleGun` set to true, but I think we should handle this better. In particular this workaround is not optimal in "real" events. 

Maybe changing the comparison from `!=` to `>` is good enough, maybe we do want a flag for this? The `usingParticleGun` flag should be obsolete anyway as `ddsim` also sets the generator status to 1 for gun particles.

I can open a PR for these changes if no one complains already now :)

**Comment by gaede** [comment]
Not sure, one always wants to draw all particles created in simulation. How about introducing a flag _drawMCParticlesCreatedInSimulation ?

**Comment by Zehvogel** [comment]
Yes I will also add a flag, otherwise this can result in pure chaos when not adjusting the minimum energy cut accordingly

![image](https://github.com/user-attachments/assets/2a2bf1b4-12ff-4b08-a89b-d74688e658f2)

**Comment by Zehvogel** [comment]
Some notes for documentary purposes:

> Yes I will also add a flag, otherwise this can result in pure chaos when not adjusting the minimum energy cut accordingly
> 
> ![image](https://github.com/user-attachments/assets/2a2bf1b4-12ff-4b08-a89b-d74688e658f2)

Looking at this particular event display again, I notice that it actually mainly shows two other issues.
If I remember it correctly, I made it by shooting a multi-GeV photon into the CLD LumiCal.
- As this was before https://github.com/key4hep/k4geo/pull/369, the LumiCal was included in the tracking region, i.e. the whole calorimeter shower was stored as secondary MC particles.
- This chaos was intensified by #32 drawing every neutral particle all the way to the other calorimeters.
