### ISSUE TITLE
ced2go seg-faulting in iLCSoft v02-00-02

### ISSUE THREAD

**Issue by beyerja** [iLCSoft/CEDViewer#8]
I currently am unable to open an event display with ced2go.

 - OS version: naf-ilc11 / Scientific Linux release 6.10 (Carbon) 
 - Compiler version: gcc (GCC) 4.9.3
 - Package version: /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-02/CEDViewer/v01-16/bin/ced2go
 - Reproduced by: run 
  ```bash 
ced2go -d $lcgeo_DIR/ILD/compact/ILD_l5_o1_v02/ILD_l5_o1_v02.xml -v DSTViewer /pnfs/desy.de/ilc/prod/ilc/mc-opt-3/ild/dst-merged/1000-B1b_ws/6f_vvWW/ILD_l5_o1_v02/v02-00-02/rv02-00-02.sv02-00-02.mILD_l5_o1_v02.E1000-B1b_ws.I35867.Pvvxyyx.eL.pR.n001.d_dstm_11117_1.slcio
```
 - Input: /pnfs/desy.de/ilc/prod/ilc/mc-opt-3/ild/dst-merged/1000-B1b_ws/6f_vvWW/ILD_l5_o1_v02/v02-00-02/rv02-00-02.sv02-00-02.mILD_l5_o1_v02.E1000-B1b_ws.I35867.Pvvxyyx.eL.pR.n001.d_dstm_11117_1.slcio
 - Output: I'm attaching the log file to the issue.
 - Goal: Want to open an event display for ILD.
[ilcsoftv02-00-02_ced2go.log](https://github.com/iLCSoft/CEDViewer/files/2465195/ilcsoftv02-00-02_ced2go.log)

**Comment by beyerja** [comment]
Update:
If I run it using the individual steps of the DSTViewer as described in https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/README.md it works. It does Not work if I try to run it with the non-DST viewer (as expected I guess). 
So there may be something wrong with how I tell ced2go to use the DSTViewer? Or something wrong in how this parameter is read in?

**Comment by rete** [comment]
Thanks for reporting this issue. I have investigated and found the following things:
- the **ced2go** python script reads your viewer argument (`-v DSTViewer`) and try to replace the key `$Viewer` in the template steering file (namely *ced2go-template-DD4.xml* in this case). By looking at the template steering file, it seems that there is no such key for replacement. This template file is designed for CEDViewer only, so REC files only.
- the DST viewer processor still uses the Gear file for geometry display. @gaede Is there a particular reason why the DSTViewer still uses Gear ? Just a forgotten transition to DD4hep I guess ... 
So you can't use the DST viewer with DD4hep geometry.

Current workaround:
- Convert geometry to Gear:
```shell
convertToGear default $lcgeo_DIR/ILD/compact/ILD_l5_o1_v02/ILD_l5_o1_v02.xml
```
- Don't use ced2go, but the commands in two steps:
```shell
# first event display window
glced &
# running marlin and feed with events
Marlin MarlinStdRecoViewerDST.xml \
  --global.GearXMLFile=gear_ILD_l5_o1_v02.xml \
  --global.LCIOInputFiles=your_file_DST.slcio
```
I will update the ILDConfig documentation. Thanks
